<?php

namespace Game\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BuldingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BuldingTypeRepository extends EntityRepository
{

}
