<?php

namespace Game\PlayerBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PlayerGameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerGameRepository extends EntityRepository
{

}
